# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_dls": "00_data.ipynb",
         "Tree": "01_model.ipynb",
         "sdt_init": "01_model.ipynb",
         "SDT": "01_model.ipynb",
         "SDTLoss": "02_loss.ipynb",
         "SDTCallback": "03_train.ipynb"}

modules = ["data.py",
           "model.py",
           "loss.py",
           "train.py"]

doc_url = "https://numb3r33.github.io/sdt/"

git_url = "https://github.com/numb3r33/sdt/tree/main/"

def custom_doc_links(name): return None
