# AUTOGENERATED! DO NOT EDIT! File to edit: 03_train.ipynb (unless otherwise specified).

__all__ = ['SDTCallback']

# Cell
from fastai.vision.all import *

from sdt.data  import *
from .model import *
from sdt.loss  import *

# Cell
class SDTCallback(Callback):
  run_before=Recorder

  def __init__(self, tree, n_leaves, prob=1.):
    self.tree     = tree
    self.n_leaves = n_leaves
    self.prob     = prob

  def after_pred(self):
    self.learn.path_prob, self.learn.pred = self.pred
    self.learn.loss_func.set_path_prob(self.path_prob)
    self.learn.loss_func.set_regularizer(self.learn.model.get_numers,
                                    self.learn.model.get_denoms
                                    )
    self.learn.model.reset()

  def after_loss(self):
    path_prob, outs = self.path_prob, self.pred
    target_indices  = path_prob.argmax(dim=1)
    max_path_prob   = outs[torch.arange(outs.shape[0]), target_indices]
    pred_target     = max_path_prob.argmax(dim=1)

    self.learn.pred = pred_target